TOP=../../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#================================================
# Build GoogleTest libraries gtest and gtest_main

LIBRARY_HOST += gtest
LIBRARY_HOST += gtest_main

SRC_DIRS += ../..

gtest_SRCS += gtest-all.cc
gtest_main_SRCS += gtest_main.cc

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
