TOP=../../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#================================================
# Build Google Mock libraries gmock and gmock_main

LIBRARY_HOST += gmock
LIBRARY_HOST += gmock_main

SRC_DIRS += ../..

gmock_SRCS += gmock-all.cc
gmock_main_SRCS += gmock_main.cc

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
